In [8]:
import numpy as np

In [9]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [20]:
rev_q2 = np.array([[10,12,9],[12,33,13]],dtype=np.float64)
rev_q2.ndim

2

In [21]:
print(rev_q2[1,1])

33.0


In [22]:
rev_q2[1,1]=14

In [23]:
print(rev_q2[1,1])

14.0


In [24]:
rev_q2.dtype

dtype('float64')

In [25]:
rev_q2.nbytes

48

In [27]:
rev_q2.itemsize

8

In [28]:
rev_q2.size

6

In [29]:
rev_q2.shape

(2, 3)

In [31]:
np.sort(rev_q2)

array([[ 9., 10., 12.],
       [12., 13., 14.]])

In [32]:
np.sort(rev_q2,axis=None)

array([ 9., 10., 12., 12., 13., 14.])

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.arange(4)

array([0, 1, 2, 3])

In [39]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [47]:
np.linspace(10,20,20) # Return evenly spaced numbers over a specified interval.

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [54]:
rev_q2.ravel() # Matlab old aur new array same memory share kar rahe hain => if change new array then old array also get changed

array([10., 12.,  9., 12., 14., 13.])

In [55]:
rev_q2.flatten() # naya array create hota hai (duplicate)

array([10., 12.,  9., 12., 14., 13.])

In [58]:
rev_q2.reshape(3,2)

array([[10., 12.],
       [ 9., 12.],
       [14., 13.]])

In [59]:
rev_q2

array([[10., 12.,  9.],
       [12., 14., 13.]])

In [64]:
print(rev_q2.min())

9.0


In [63]:
print(rev_q2.max())

14.0


In [65]:
rev_q2.sum()

np.float64(70.0)

In [68]:
rev_q2.sum(axis=0) # Sum of columns

array([22., 26., 22.])

In [69]:
rev_q2.sum(axis=1) # Sum of rows

array([31., 39.])

In [70]:
for row in rev_q2:
    print(row)

[10. 12.  9.]
[12. 14. 13.]


In [72]:
b = np.array([1,4,16])
b

array([ 1,  4, 16])

In [76]:
np.sqrt(b)

array([1., 2., 4.])

In [77]:
np.square(b)

array([  1,  16, 256])

In [79]:
np.std(b) # Standard Deviation

np.float64(6.48074069840786)