In [1]:
import numpy as np

In [10]:
q1=np.array([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])
q2=np.array([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

In [11]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [12]:
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [13]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [17]:
prices = np.array([
    [10,12,11],
    [8,9,10],
    [15,16,17]
])

In [18]:
q1_revenue = q1*prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [20]:
q1_discount = q1_revenue*0.2
q1_discount

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [23]:
net_revenue = q1_revenue - q1_discount
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [25]:
print(np.sum(q1_discount))

5642.0


In [28]:
features = np.array([
    [2000,3],
    [1800,2]
])
weights = np.array([150,50000])
# np.sum(features*weights)
np.dot(features,weights)

array([450000, 370000])

In [31]:
c=np.array([1,2,3])
d=np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])