In [1]:
import numpy as np

In [2]:
a=np.array([6,7,8,9])

In [3]:
# Slicing

In [4]:
a[0:2]

array([6, 7])

In [5]:
a[2:]

array([8, 9])

In [6]:
a[-1]

np.int64(9)

In [8]:
a[-2:]

array([8, 9])

In [9]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [10]:
b[1][2]

np.int64(6)

In [11]:
b[1,2]

np.int64(6)

In [12]:
b[-1]

array([7, 8, 9])

In [14]:
b[-1,0:2]

array([7, 8])

In [18]:
b[:,1:3]                                                        # Imp

array([[2, 3],
       [5, 6],
       [8, 9]])

In [20]:
c=np.array([
    [101,"Mira"],
    [102,"Omkar"],
    [103,"Andrea"]
])
d=np.array([
    [101,250.50,"2023-08-01"],
    [102,150.00,"2023-08-02"],
    [103,300.75,"2023-08-01"]
])

In [21]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Omkar', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [22]:
e=np.array([
    [104,"Vyankatesh"],
    [105,"John"],
    [106,"Kathy"]
])

In [24]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Omkar'],
       ['103', 'Andrea'],
       ['104', 'Vyankatesh'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [33]:
transactions =np.array([
    [101,"Mira",250.50,"2023-08-01"],
    [102,"Omkar",150.00,"2023-08-02"],
    [103,"Andrea",300.75,"2023-08-01"]
])
a,b=np.hsplit(transactions,[2])

In [35]:
a

array([['101', 'Mira'],
       ['102', 'Omkar'],
       ['103', 'Andrea']], dtype='<U32')

In [36]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01']], dtype='<U32')

In [38]:
x,y=np.vsplit(transactions,[2])

In [39]:
x

array([['101', 'Mira', '250.5', '2023-08-01'],
       ['102', 'Omkar', '150.0', '2023-08-02']], dtype='<U32')

In [40]:
y

array([['103', 'Andrea', '300.75', '2023-08-01']], dtype='<U32')

In [42]:
monthly_sales = np.array([30,33,35,28,42])
result=monthly_sales < 32
result

array([ True, False, False,  True, False])

In [43]:
monthly_sales[result]

array([30, 28])

In [47]:
print(monthly_sales.max())

42


In [51]:
index = np.argmax(monthly_sales)
print(index)

4


In [50]:
print(monthly_sales[index])

42


In [52]:
transactions

array([['101', 'Mira', '250.5', '2023-08-01'],
       ['102', 'Omkar', '150.0', '2023-08-02'],
       ['103', 'Andrea', '300.75', '2023-08-01']], dtype='<U32')

In [54]:
transactions[:,2].astype(float)

array([250.5 , 150.  , 300.75])

In [55]:
highest_price_index = np.argmax(transactions[:,2].astype(float))
print(highest_price_index)

2


In [62]:
transactions[:,2].astype(float)[highest_price_index]    # array([250.5 , 150.  , 300.75])[highest_price_index]

np.float64(300.75)

In [63]:
transactions[transactions[:,0]=='102']                    #Condition Inside []

array([['102', 'Omkar', '150.0', '2023-08-02']], dtype='<U32')